apiVersion: v1
entries:
  planning-poker:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-27T16:39:42.891472061Z"
    description: A real-time collaborative estimation tool for agile teams with WebSocket
      synchronization
    digest: 0aa5005d46884efdd07b5f9ec8eb4d5f1caed05158bd4a8882b9461a7db3e81d
    home: https://github.com/kjaniec-dev/planning-poker
    icon: https://raw.githubusercontent.com/kjaniec-dev/planning-poker/main/public/logo.svg
    keywords:
    - planning-poker
    - scrum
    - agile
    - estimation
    - websocket
    - realtime
    maintainers:
    - email: contact@kjaniec.dev
      name: kjaniec-dev
    name: planning-poker
    sources:
    - https://github.com/kjaniec-dev/planning-poker
    type: application
    urls:
    - https://kjaniec-dev.github.io/planning-poker/charts/planning-poker-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-27T16:39:42.890616332Z"
