apiVersion: v1
entries:
  planning-poker:
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-12-27T17:06:11.744050281Z"
    description: A real-time collaborative estimation tool for agile teams with WebSocket
      synchronization
    digest: 5bec779dc87d9389d7d9661653accdcf56d851ecbaff831dadbe6cf3a1283bcb
    home: https://github.com/kjaniec-dev/planning-poker
    icon: https://raw.githubusercontent.com/kjaniec-dev/planning-poker/main/public/logo.svg
    keywords:
    - planning-poker
    - scrum
    - agile
    - estimation
    - websocket
    - realtime
    maintainers:
    - email: contact@kjaniec.dev
      name: kjaniec-dev
    name: planning-poker
    sources:
    - https://github.com/kjaniec-dev/planning-poker
    type: application
    urls:
    - https://kjaniec-dev.github.io/planning-poker/charts/planning-poker-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-27T17:06:11.743367883Z"
    description: A real-time collaborative estimation tool for agile teams with WebSocket
      synchronization
    digest: 722cd75c67f50151afd2349774b2af49df1aeb531e93ed2de7d79c62bfceec5e
    home: https://github.com/kjaniec-dev/planning-poker
    icon: https://raw.githubusercontent.com/kjaniec-dev/planning-poker/main/public/logo.svg
    keywords:
    - planning-poker
    - scrum
    - agile
    - estimation
    - websocket
    - realtime
    maintainers:
    - email: contact@kjaniec.dev
      name: kjaniec-dev
    name: planning-poker
    sources:
    - https://github.com/kjaniec-dev/planning-poker
    type: application
    urls:
    - https://kjaniec-dev.github.io/planning-poker/charts/planning-poker-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-27T17:06:11.742508783Z"
